### ISSUE TITLE
npm install fails becasue of "fs": "0.0.2"

### ISSUE THREAD

**Issue by brahmos** [hps/heartland-nodejs#11]
Looks like package.json is referencing ```"fs": "0.0.2"``` and its casuing the npm install to fail. Here is the error

```
pm ERR! Error: version not found: fs@0.0.2
npm ERR!     at /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.10.32/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.10.32/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

```

Looks like there is a discussion on this topic, you need to remove that reference as fs is part of the core.

https://github.com/npm/npm/issues/13743

**Comment by seandesmond** [comment]
Hey @brahmos & @slogsdon I can look into this if y'all want. I've working working in that repo anyway. Give me the green light and I'll have at it!

**Comment by slogsdon** [comment]
Thanks for the report, @brahmos! We'll get this corrected.

**Comment by slogsdon** [comment]
@brahmos It looks like the npm team reverted the change, adding the `fs` package back to npm indefinitely. Your builds should continue to work, but we are also removing the `fs` package from our `package.json`. I'll leave this open until we publish that change.
